/**
 * All project constants
 * @module utils/constants
*/

const OS = require('./OS');
const os = new OS();

module.exports = {
  error:{
    INVALID_X: 'The X value sent is invalid.',
    INVALID_Y: 'The Y value sent is invalid.',
    INVALID_SCREEN_POSITION: 'The point [x, y] is not valid in this screen resolution.',
    INVALID_MOUSE_BUTTON: 'The mouse button sent is not valid.',
    INVALID_KEYBOARD_KEY: 'The keyboard key sent is not valid.',
    INVALID_STRING: 'The string sent is not valid.'
  },
  input: {
    HUMAN_TIME_REACTION_MIN: 115,
    HUMAN_TIME_REACTION_MAX: 170,
    PIXELS_PER_TICK: 1,
    mouse: {
      LEFT: 'LEFT',
      RIGHT: 'RIGHT',
      MIDDLE: 'MIDDLE'
    },
    keyboard: {
      ESC: 'ESC',
      F1: 'F1',
      F2: 'F2',
      F3: 'F3',
      F4: 'F4',
      F5: 'F5',
      F6: 'F6',
      F7: 'F7',
      F8: 'F8',
      F9: 'F9',
      F10: 'F10',
      F11: 'F11',
      F12: 'F12',
      TIO: '~',
      ONE: '1',
      TWO: '2',
      THREE: '3',
      FOUR: '4',
      FIVE: '5',
      SIX: '6',
      SEVEN: '7',
      EIGHT: '8',
      NINE: '9',
      ZERO: '0',
      MINUS: '-',
      EQUALS: '=',
      BACKSLASH: '\\',
      BACKSPACE: 'BACKSPACE',
      TAB: 'TAB',
      Q: 'Q',
      W: 'W',
      E: 'E',
      R: 'R',
      T: 'T',
      Y: 'Y',
      U: 'U',
      I: 'I',
      O: 'O',
      P: 'P',
      OPEN_BRACKET: '[',
      CLOSE_BRACKET: ']',
      ENTER: 'ENTER',
      CAPSLOCK: 'CAPSLOCK',
      A: 'A',
      S: 'S',
      D: 'D',
      F: 'F',
      G: 'G',
      H: 'H',
      J: 'J',
      K: 'K',
      L: 'L',
      SEMICOLON: ';',
      SINGLE_QUOTATION: '\'',
      LEFT_SHIFT: 'LSHIFT',
      Z: 'Z',
      X: 'X',
      C: 'C',
      V: 'V',
      N: 'B',
      N: 'N',
      M: 'M',
      COMMA: ',',
      DOT: '.',
      SLASH: '/',
      RIGHT_SHIFT: 'RSHIFT',
      LEFT_CONTROL: 'LCTRL',
      LEFT_WINDOWS: 'LWIN',
      LEFT_ALT: 'LALT',
      SPACe: 'SPACE',
      RIGHT_ALT: 'RALT',
      RIGHT_WINDOWS: 'RWIN',
      FN: 'FN',
      RIGHT_CONTROL: 'RCTRL',
      PRINT_SCREEN: 'PRINTSCREEN',
      SCROOL_LOCK: 'SCROLLLOCK',
      PAUSE_BREAK: 'PAUSEBREAK',
      INSERT: 'INSERT',
      HOME: 'HOME',
      PAGE_UP: 'PAGEUP',
      DELETE: 'DELETE',
      END: 'END',
      PAGE_DOWN: 'PAGEDOWN',
      UP: 'UP',
      LEFT: 'LEFT',
      DOWN: 'DOWN',
      RIGHT: 'RIGHT',
      NUMPAD_ZERO: 'NUMPAD0',
      NUMPAD_ONE: 'NUMPAD1',
      NUMPAD_TWO: 'NUMPAD2',
      NUMPAD_THREE: 'NUMPAD3',
      NUMPAD_FOUR: 'NUMPAD4',
      NUMPAD_FIVE: 'NUMPAD5',
      NUMPAD_SIX: 'NUMPAD6',
      NUMPAD_SEVEN: 'NUMPAD7',
      NUMPAD_EIGHT: 'NUMPAD8',
      NUMPAD_NINE: 'NUMPAD9',
      NUM_LOCK: 'NUMLOCK',
      NUMPAD_SLASH: 'NUMPAD/',
      ASTERISK: '*',
      NUMPAD_MINUS: 'NUMPAD-',
      NUMPAD_PLUS: '+',
      NUMPAD_ENTER: 'NUMPADENTER',
      NUMPAD_DOT: 'NUMPAD.'
    }
  }
};
